services:
  postgres:
    image: postgres:16
    container_name: datingapp-db
    restart: always
    environment:
      POSTGRES_DB: datingapp
      POSTGRES_USER: appuser
      POSTGRES_PASSWORD: secret123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
